import type { Metadata } from "next";
import "./globals.css";
import React from "react";
import Navbar, { NAVBAR_HEIGHT } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div style={{ paddingTop: NAVBAR_HEIGHT }}>
          {children}
        </div>
      </body>
    </html>
  );
}
