"use client"
//import type { Metadata } from "next";
import "./globals.css";
import React, {useEffect} from "react";
import Navbar, { NAVBAR_HEIGHT } from "@/components/Navbar";
import UseAuthStore from "@/store/useAuthStore";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // @ts-ignore
  const {initializeAuth} = UseAuthStore();
  useEffect(() => {
    initializeAuth();
  }, []);
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div style={{ paddingTop: NAVBAR_HEIGHT }}>
          {children}
        </div>
      </body>
    </html>
  );
}
