export const geoJson = {
    "万州区": "https://geo.datav.aliyun.com/areas_v3/bound/500101.json",
    "黔江区": "https://geo.datav.aliyun.com/areas_v3/bound/500114.json",
    "涪陵区": "https://geo.datav.aliyun.com/areas_v3/bound/500102.json",
    "渝中区": "https://geo.datav.aliyun.com/areas_v3/bound/500103.json",
    "大渡口区": "https://geo.datav.aliyun.com/areas_v3/bound/500104.json",
    "江北区": "https://geo.datav.aliyun.com/areas_v3/bound/500105.json",
    "沙坪坝区": "https://geo.datav.aliyun.com/areas_v3/bound/500106.json",
    "九龙坡区": "https://geo.datav.aliyun.com/areas_v3/bound/500107.json",
    "南岸区": "https://geo.datav.aliyun.com/areas_v3/bound/500108.json",
    "北碚区": "https://geo.datav.aliyun.com/areas_v3/bound/500109.json",
    "渝北区": "https://geo.datav.aliyun.com/areas_v3/bound/500112.json",
    "巴南区": "https://geo.datav.aliyun.com/areas_v3/bound/500113.json",
    "长寿区": "https://geo.datav.aliyun.com/areas_v3/bound/500115.json",
    "江津区": "https://geo.datav.aliyun.com/areas_v3/bound/500116.json",
    "合川区": "https://geo.datav.aliyun.com/areas_v3/bound/500117.json",
    "永川区": "https://geo.datav.aliyun.com/areas_v3/bound/500118.json",
    "南川区": "https://geo.datav.aliyun.com/areas_v3/bound/500119.json",
    "綦江区": "https://geo.datav.aliyun.com/areas_v3/bound/500110.json",
    "大足区": "https://geo.datav.aliyun.com/areas_v3/bound/500111.json",
    "璧山区": "https://geo.datav.aliyun.com/areas_v3/bound/500120.json",
    "铜梁区": "https://geo.datav.aliyun.com/areas_v3/bound/500151.json",
    "潼南区": "https://geo.datav.aliyun.com/areas_v3/bound/500152.json",
    "荣昌区": "https://geo.datav.aliyun.com/areas_v3/bound/500153.json",
    "开州区": "https://geo.datav.aliyun.com/areas_v3/bound/500154.json",
    "梁平区": "https://geo.datav.aliyun.com/areas_v3/bound/500155.json",
    "武隆区": "https://geo.datav.aliyun.com/areas_v3/bound/500156.json",

    "城口县": "https://geo.datav.aliyun.com/areas_v3/bound/500229.json",
    "丰都县": "https://geo.datav.aliyun.com/areas_v3/bound/500230.json",
    "垫江县": "https://geo.datav.aliyun.com/areas_v3/bound/500231.json",
    "忠县": "https://geo.datav.aliyun.com/areas_v3/bound/500233.json",
    "云阳县": "https://geo.datav.aliyun.com/areas_v3/bound/500235.json",
    "奉节县": "https://geo.datav.aliyun.com/areas_v3/bound/500236.json",
    "巫山县": "https://geo.datav.aliyun.com/areas_v3/bound/500237.json",
    "巫溪县": "https://geo.datav.aliyun.com/areas_v3/bound/500238.json",

    "石柱土家族自治县": "https://geo.datav.aliyun.com/areas_v3/bound/500240.json",
    "秀山土家族苗族自治县":"https://geo.datav.aliyun.com/areas_v3/bound/500241.json",
    "酉阳土家族苗族自治县":"https://geo.datav.aliyun.com/areas_v3/bound/500242.json",
    "彭水苗族土家族自治县":"https://geo.datav.aliyun.com/areas_v3/bound/500243.json",
}